openapi: 3.0.1
info:
  description: useridentity_descripton
  title: useridentity
  version: 0.0.1
servers:
- description: Generated server url
  url: http://localhost:6969
paths:
  /system/healthcheck:
    get:
      operationId: healthcheck
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - system-controller
      x-accepts: '*/*'
  /users/{id}:
    post:
      operationId: getUser
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: OK
      tags:
      - user-controller
      x-accepts: '*/*'
  /login:
    post:
      description: Login user
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LoginUserResponse'
          description: successful operation
      summary: Login user
      tags:
      - open
      x-contentType: application/json
      x-accepts: '*/*'
  /register:
    post:
      description: Register a new user
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        "201":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RegisterUserResponse'
          description: successful operation
      summary: Register user
      tags:
      - open
      x-contentType: application/json
      x-accepts: '*/*'
components:
  schemas:
    User:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        phoneNumber: phoneNumber
        isValidated: true
        id: id
        username: username
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        username:
          type: string
        phoneNumber:
          type: string
        isValidated:
          type: boolean
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      type: object
    UserResponse:
      example:
        data:
          createdAt: 2000-01-23T04:56:07.000+00:00
          phoneNumber: phoneNumber
          isValidated: true
          id: id
          username: username
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          $ref: '#/components/schemas/User'
      type: object
    LoginRequest:
      example:
        password: password
        phoneNumber: phoneNumber
        username: username
      properties:
        phoneNumber:
          type: string
        username:
          type: string
        password:
          type: string
      required:
      - password
      type: object
    LoginUser:
      example:
        id: id
        accessToken: accessToken
      properties:
        id:
          type: string
        accessToken:
          type: string
      type: object
    LoginUserResponse:
      example:
        data:
          id: id
          accessToken: accessToken
      properties:
        data:
          $ref: '#/components/schemas/LoginUser'
      type: object
    RegisterRequest:
      example:
        password: password
        phoneNumber: phoneNumber
      properties:
        phoneNumber:
          type: string
        password:
          maxLength: 16
          minLength: 8
          type: string
      required:
      - password
      - phoneNumber
      type: object
    CreateUser:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        phoneNumber: phoneNumber
        isValidated: true
        id: id
        accessToken: accessToken
        username: username
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        username:
          type: string
        phoneNumber:
          type: string
        isValidated:
          type: boolean
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
        accessToken:
          type: string
      type: object
    RegisterUserResponse:
      example:
        data:
          createdAt: 2000-01-23T04:56:07.000+00:00
          phoneNumber: phoneNumber
          isValidated: true
          id: id
          accessToken: accessToken
          username: username
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          $ref: '#/components/schemas/CreateUser'
      type: object

